name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run lint
      run: npm run lint && npm run prettify     
    - name: Run typescript
      run: npx tsc   
    - name: Run Tests
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # this is just an example, this could be any command that will trigger jest
        test-command: "npm test"
