name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run lint
      run: npm run lint && npm run prettify     
    - name: Run typescript
      run: npx tsc   
    - name: Run Tests
      uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "npm test -- --coverage"
