name: 'Jest'
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Comment with Test Coverage
      uses: dkershner6/jest-coverage-commenter-action@v1
      with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          test_command: "npm test"
