name: 'Jest'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
      - run: npm ci
      - name: TestCoverage
        id: testCovergae
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false // defaults to false, if made true whole coverage report is commented with the diff
          runCommand: "npx jest --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles test/.*test.*"
          delta: 0.5
