name: Lighthouse
on: [pull_request]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse Master
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.atticodellino.com
#           budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Lighthouse report: ${{ steps.LHCIAction.outputs.links['https://www.atticodellino.com/']}}" 
          check_for_duplicate_msg: true  # OPTIONAL 
         # ${{steps.LHCIAction.outputs.links}}
