name: Lighthouse
on: [pull_request]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse Master
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.atticodellino.com
#           budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Create Lighthouse comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            Lighthouse report
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
