name: Vercel Master
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: now-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
      - name: Checkout 🛎
        uses: actions/checkout@v1
      - name: Run Cypress 🌲 Master
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: https://www.atticodellino.com
          CYPRESS_RECORD_KEY:  ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: false
          start: npm start
          working-directory: cypress
      - name: Lighthouse Master
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.atticodellino.com
#           budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
